POST http://localhost:3333/api/v1/fisical-person
Content-Type: application/json

{
  "name": "Luis Eduardo",
  "email": "luis.ratis04@gmail.com",
  "password": "luis.ratis04"
}

###
POST http://localhost:3333/api/v1/legal-person
Content-Type: application/json

{
  "name": "A. C. D. A. IMPORTACAO E EXPORTACAO LTDA",
  "email": "araujo@araujosuper.com.br",
  "password": "507002",
  "cnpj": "16.513.207/0001-08"
}

###
POST http://localhost:3333/api/v1/service
Content-Type: application/json

{
  "title": "Venda de alimentos",
  "description": "O comércio varejista de mercadorias em geral, com predominância de produtos alimentícios é a classe que se encontram os supermercados (tecnicamente, com área de venda variando de trezentos a cinco mil metros quadrados). Atendem o público em geral, especialmente pessoas físicas. Apesar dos produtos alimentícios representarem a principal categoria comercial, também comercializam produtos de higiene e limpeza, vestuário, ferragens, utensílios domésticos e até mesmo eletroeletrônicos e eletrodomésticos.",
  "legal_person_id": "1"
}

###
POST http://localhost:3333/api/v1/hire
Content-Type: application/json

{
  "service_id": "1",
  "fisical_person_id": "1"
}

###
POST http://localhost:3333/api/v1/assess
Content-Type: application/json

{
  "fisical_person_id": "1",
  "service_id": "1",
  "value": "4"
}

###
GET http://localhost:3333/api/v1/login/fisical-person
Content-Type: application/json

{
  "user": "luis.ratis04@gmail.com",
  "password": "luis.ratis04"
}

###
GET http://localhost:3333/api/v1/login/fisical-person
Content-Type: application/json

{
  "user": "luis.ratis04@gmail.com",
  "password": "senhaincorreta"
}
